### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/document-conversion-nodejs#44]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
	npm ERR! Linux 4.2.0-27-generic
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
	npm ERR! node v4.4.4
	npm ERR! npm  v2.15.1
	npm ERR! code EPEERINVALID

	npm ERR! peerinvalid The package react@15.4.0 does not satisfy its siblings' peerDependencies requirements!
	npm ERR! peerinvalid Peer express-react-views@0.10.2 wants react@^0.14.0 || ^15.0.0
	npm ERR! peerinvalid Peer react-addons-pure-render-mixin@15.4.0 wants react@^15.4.0
	npm ERR! peerinvalid Peer react-dom@15.4.0 wants react@^15.4.0
	npm ERR! peerinvalid Peer react-prism@3.2.2 wants react@^0.14.6 || ^15.0.0
	npm ERR! peerinvalid Peer watson-react-components@0.0.17 wants react@~0.14 || ~15.3.0

**Comment by germanattanasio** [comment]
I just deployed the app without problem @johnfelipe. Make sure you run `npm install .`
