### ISSUE TITLE
increase size of file for upload?

### ISSUE THREAD

**Issue by johnfelipe** [watson-developer-cloud/document-conversion-nodejs#45]
Is possilbe increase size to 10 mb?

**Comment by germanattanasio** [comment]
It's but for this demo we prefer to keep it as it is. What's your use case?

**Comment by johnfelipe** [comment]
Is for convert senate Hansard to txt.

**Comment by johnfelipe** [comment]
@germanattanasio i need to convert hansard (actas) to txt, and word or pdf is more sized

**Comment by germanattanasio** [comment]
Hi @johnfelipe I discussed the limitation with the team and the decision is to keep the existing one. you can deploy this app with your own service instance and remove the limitation by commenting [this line](https://github.com/watson-developer-cloud/document-conversion-nodejs/blob/602a9e2d7453847eb4056a08d6709a66674a15bc/views/upload-form.jsx#L28)
